// <auto-generated />
using System;
using CarStore.Shop.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarStore.Shop.Infrastructure.Migrations.LogCarShop
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20231027122507_AddTableLog")]
    partial class AddTableLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarStore.Core.DomainObjects.LogError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("ErrorFull")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Query")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("Pk_LogErrors_Id");

                    b.ToTable("__LogErrors", (string)null);
                });

            modelBuilder.Entity("CarStore.Core.DomainObjects.LogRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Device")
                        .HasMaxLength(600)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("interval");

                    b.Property<string>("Header")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Host")
                        .HasMaxLength(600)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Ip")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Method")
                        .HasMaxLength(600)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Path")
                        .HasMaxLength(600)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Query")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<string>("Response")
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(600)
                        .IsUnicode(false)
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("Pk_LogRequests_Id");

                    b.ToTable("__LogRequests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
